# Generated by Django 3.2.12 on 2022-07-07 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='users_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
