# Generated by Django 3.2.12 on 2022-07-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_auto_20220709_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, verbose_name='About'),
        ),
    ]
