# Generated by Django 3.2.12 on 2022-07-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='joined',
            field=models.DateTimeField(),
        ),
    ]
